var constants = {
  SET_COUNTDOWN: "SET_COUNTDOWN",
  START_COUNTDOWN: "START_COUNTDOWN",
  STOP_COUNTDOWN: "STOP_COUNTDOWN",
  RESET_COUNTDOWN: "RESET_COUNTDOWN",

  SET_STOPWATCH: "SET_STOPWATCH",
  START_STOPWATCH: "START_STOPWATCH",
  STOP_STOPWATCH: "STOP_STOPWATCH",
  RESET_STOPWATCH: "RESET_STOPWATCH",

  SET_VIDEO_RECORDER_STATUS: "SET_VIDEO_RECORDER_STATUS",
  SET_RECORDED_VIDEO_TOKEN: "SET_RECORDED_VIDEO_TOKEN"
};
