
# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
defaults: &defaults
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
  ziggeo_api_token: <%= ENV["ZIGGEO_API_TOKEN"] %>
  ziggeo_private_key: <%= ENV["ZIGGEO_PRIVATE_KEY"] %>
  ziggeo_encryption_key: <%= ENV["ZIGGEO_ENCRYPTION_KEY"] %>

development: *defaults

test: *defaults

# Do not keep production secrets in the repository,
# instead read values from the environment.
production: *defaults
